name: pnpm build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Authenticate with private NPM package
      run: echo "//pkgs.dev.azure.com/cznl/_packaging/CZ/npm/registry/:_authToken=${{ secrets.CZ_REGISTRY_TOKEN }}" > ~/.npmrc
    - name: Install dependencies
      run: pnpm install
